In [2]:
import tensorflow as tf

In [3]:
const_1=tf.constant(127,dtype='int8')
const_1

<tf.Tensor: shape=(), dtype=int8, numpy=127>

In [4]:
const_1.numpy()

127

In [5]:
const_1.shape

TensorShape([])

# Vectors

In [6]:
const_2=tf.constant([2.,4.,6.,8.,11.,13],dtype='float16')
print(const_2)

tf.Tensor([ 2.  4.  6.  8. 11. 13.], shape=(6,), dtype=float16)


In [7]:
const_2.numpy()

array([ 2.,  4.,  6.,  8., 11., 13.], dtype=float16)

# Tensor Matrix
- Rank 2 Tensor

In [ ]:
tf.constant([[[10,20,30],
            [30,40,50],
            [40,60,70]],

            [[10,20,30],
            [30,40,50],
            [40,60,70]],

            [[10,20,30],
            [30,40,50],
            [40,60,70]]],dtype='int8')

<tf.Tensor: shape=(3, 3, 3), dtype=int8, numpy=
array([[[10, 20, 30],
        [30, 40, 50],
        [40, 60, 70]],

       [[10, 20, 30],
        [30, 40, 50],
        [40, 60, 70]],

       [[10, 20, 30],
        [30, 40, 50],
        [40, 60, 70]]], dtype=int8)>

In [ ]:
var_1=tf.Variable(0,dtype='int8')
var_1

<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=0>

In [ ]:
var_2=tf.Variable([2.,4.,6.,8.,11.,13],dtype='float16')
var_2

<tf.Variable 'Variable:0' shape=(6,) dtype=float16, numpy=array([ 2.,  4.,  6.,  8., 11., 13.], dtype=float16)>

In [ ]:
weights=tf.Variable([[10],
                    [12],
                    [13],
                    [14],
                    [15],
                    [20]],dtype='float16')

In [ ]:
x=tf.constant([[10.],
                [20.],
                [30.],
                [40.],
                [50.],
                [60.]],dtype='float16')

In [ ]:
wt=tf.transpose(weights)
wt

<tf.Tensor: shape=(1, 6), dtype=float16, numpy=array([[10., 12., 13., 14., 15., 20.]], dtype=float16)>

In [ ]:
tf.tensordot(wt,x,axes=1)

<tf.Tensor: shape=(1, 1), dtype=float16, numpy=array([[3240.]], dtype=float16)>

In [ ]:
tf.tensordot(x,wt,axes=1)

<tf.Tensor: shape=(6, 6), dtype=float16, numpy=
array([[ 100.,  120.,  130.,  140.,  150.,  200.],
       [ 200.,  240.,  260.,  280.,  300.,  400.],
       [ 300.,  360.,  390.,  420.,  450.,  600.],
       [ 400.,  480.,  520.,  560.,  600.,  800.],
       [ 500.,  600.,  650.,  700.,  750., 1000.],
       [ 600.,  720.,  780.,  840.,  900., 1200.]], dtype=float16)>

In [ ]:
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.optimizers import RMSprop 


In [ ]:
def build_model():
    model=Sequential()
    model.add(Dense(units=4,activation='relu',input_shape=[8]))
    model.add(Dense(units=8,activation='relu'))
    model.add(Dense(units=1))
    model.compile(loss='mean_squared_error')
    model.compile(loss='mean_squared_error',optimizer='RMSProp',metrics=['mean_squared_error'])
    return model

In [ ]:
model=build_model()

In [ ]:
model.summary()